version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    #volumes allow to store in a persistent disk the content in a local disk
    #db_data is a volume created by docker directly
    volumes:
      - mariadb_data:/var/lib/mysql
    # in case of problem we restart automatically the container
    networks:
      - network
    ports:
      - 3306:3306
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    #Create a depedency between the 2 container, db will be launched before
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: dockerfile
    restart: always
    env_file:
      - .env
    ports:
     - 9000:9000
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network

#BONUS PART
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    ports:
     - '6379:6379'
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network

  ftp-server:
    build:
      context: ./bonus/ftp_server
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    build: requirements/bonus/ftp_server
    container_name: ftp-server
    ports: ['7042:7042']
    volumes:
      - "wordpress_data:/var/www/html"
    networks:
      - network
    restart: always
    env_file:
      - .env


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/vbachele/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/vbachele/data/wordpress
      o: bind

networks:
  network:
    driver: bridge